login_link.onclick=()=>{
    login_page();
}
generate_rand_math(registration_form_arithmetic_test);
upload_photo(register_file,register_img_overview,uploaded_img_name);
validate_registration_details(
    register_fullname,
    register_id_number,
    register_age,
    register_county,
    male_gender,
    female_gender,
    other_gender,
    selected_country,
    register_telephone,
    register_email,
    register_password,
    register_confirm_password,
    register_sum_result,
    registration_send_code,
    register_verification_code,
    submit_registration_form,
    uploaded_img_name
);
display_flags(selected_country);
var test = "hello wolrd"
console.log(test.slice(1));